def main():
    if __name__ == "__main__":
        database = ["ABACAXI", "ELEFANTE", "COMPUTADOR", "GIRAFA", "ESPELHO", "CARRO", "ABAJUR", "BANANA", "GUITARRA", "XADREZ", "FOTOGRAFIA", "HIPOPOTAMO", "JANELA", "TIGRE", "UVA", "CANETA", "FUTEBOL", "PARAQUEDAS", "TURBINA", "PIANO", "MORANGO", "CACHORRO", "TECLADO", "MORCEGO", "COELHO", "CHOCOLATE", "PAPAGAIO", "DINOSSAURO", "BICICLETA", "CANECA", "MACA", "LAMPADA", "SAPO", "MONTANHA", "BARCO", "ZEBRA", "GARRAFA", "CAMISETA", "SUSHI", "NAVIO", "GAFANHOTO", "LIVRO", "SKATE", "ELETRICIDADE", "PLANETA", "FOGUETE", "VENTILADOR", "PEDRA", "VELA", "CADEIRA"]


main()